# global:
#   scrape_interval: 5s

# scrape_configs:
#   - job_name: "dotnet_app"
#     scrape_interval: 5s
#     static_configs:
#       - targets: ["app:8080"]

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']
