extensions:
  health_check:
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  zipkin:

processors:
  batch:

exporters:
  debug:
  file/traces:
    path: /log/otel/traces.log
  file/metrics:
    path: /log/otel/metrics.log
  file/logs:
    path: /log/otel/logs.log
  otlp:
    endpoint: "${JAEGER_ENDPOINT}"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
  loki:
    endpoint: "${LOKI_ENDPOINT}"
    tls:
      insecure: true
  zipkin:
    endpoint: "${ZIPKIN_ENDPOINT}"
    tls:
      insecure: true
  otlphttp: 
    endpoint: "${SEQ_LOG_ENDPOINT}"
    tls:
      insecure: true

  # otlphttptrace: 
  #   endpoint: "${SEQ_TRACE_ENDPOINT}"

service:
  pipelines:
    traces:
      receivers:
        - otlp
        - zipkin
      processors: [batch]
      exporters:
        # - debug 
        - file/traces
        - otlp
        - zipkin
        #- otlphttp
    metrics:
      receivers:
        - otlp
      processors: [batch]
      exporters:
        # - debug
        - file/metrics
        - prometheus
    logs:
      receivers:
        - otlp
      processors: [batch]
      exporters:
        - debug 
        - file/logs
        - loki
        - otlphttp

  extensions:
    - health_check
    - zpages
