extensions:
  health_check:
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  zipkin:

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  file/traces:
    path: /log/otel/traces.log
  file/metrics:
    path: /log/otel/metrics.log
  file/logs:
    path: /log/otel/logs.log
  otlp/jaeger:
    endpoint: "${JAEGER_ENDPOINT}"
    tls:
      insecure: true
  prometheus:
    endpoint: "${PROMETHEUS_ENDPOINT}"
  loki:
    endpoint: "${LOKI_ENDPOINT}"
    tls:
      insecure: true
  zipkin:
    endpoint: "${ZIPKIN_ENDPOINT}"
    tls:
      insecure: true
  otlp/aspire:
    endpoint: "${ASPIRE_ENDPOINT}"
    # compression: none
    tls:
      insecure: true
  otlphttp/seq:
    endpoint: "${SEQ_ENDPOINT}"
    compression: gzip
    tls:
      insecure: true
  ## otlphttp/seq:
  #   endpoint: "${SEQ_ENDPOINT}"
  #   tls:
  #     insecure: true




service:
  pipelines:
    traces:
      receivers: [otlp, zipkin]
      processors: [batch]
      exporters: [debug, file/traces, otlp/jaeger, zipkin, otlp/aspire]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, file/metrics, prometheus, otlp/aspire]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, file/logs, loki, otlphttp/seq, otlp/aspire]

  extensions:
    - health_check
    - zpages
